#! /usr/bin/bash

export BUILD_EXCLUDES='qt_gui_cpp rqt_gui_cpp qt_gui_core rqt rosidl_generator_cpp rosidl_default_generators rosidl_generator_py rosidl_typesupport_fastrtps_cpp rosidl_typesupport_introspection_cpp rosidl_typesupport_introspection_tests'

ARENA_WS_DIR="$(pwd)"

source $(cd src/arena/arena-rosnav && poetry env info -p)/bin/activate
colcon build \
    --symlink-install \
    --continue-on-error \
    --packages-skip-build-finished \
    --cmake-args " -DPython3_ROOT_DIR=$(cd src/arena/arena-rosnav && poetry env info -p)" \
    --packages-skip ${BUILD_EXCLUDES} \
    "$@"

cd $ARENA_WS_DIR
source install/local_setup.bash
